//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use improvie_logic::constant::items::ContentKind;
use sea_orm::entity::prelude::*;
use uid::Uid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub item_id: Uid,
    #[sea_orm(column_type = "custom(\"tinyint unsigned\")")]
    pub kind: ContentKind,
    #[sea_orm(column_type = "Text")]
    pub content_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::items::Entity",
        from = "Column::ItemId",
        to = "super::items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Items,
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
