//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hierarchical_play_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub parent_folder_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub child_id: String,
    #[sea_orm(column_type = "custom(\"int unsigned\")")]
    pub sort_order: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::play_folders::Entity",
        from = "Column::ParentFolderId",
        to = "super::play_folders::Column::ItemId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PlayFolders,
    #[sea_orm(
        belongs_to = "super::play_items::Entity",
        from = "Column::ChildId",
        to = "super::play_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PlayItems,
}

impl Related<super::play_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayFolders.def()
    }
}

impl Related<super::play_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
