//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hierarchical_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub parent_folder_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub child_id: String,
    #[sea_orm(column_type = "custom(\"int unsigned\")")]
    pub sort_order: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::ParentFolderId",
        to = "super::folders::Column::ItemId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Folders,
    #[sea_orm(
        belongs_to = "super::items::Entity",
        from = "Column::ChildId",
        to = "super::items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Items,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
