//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use improvie_logic::constant::items::ItemKind;
use sea_orm::entity::prelude::*;
use uid::Uid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub id: Uid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "custom(\"tinyint unsigned\")")]
    pub kind: ItemKind,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::contents::Entity")]
    Contents,
    #[sea_orm(has_one = "super::folders::Entity")]
    Folders,
    #[sea_orm(has_many = "super::hierarchical_items::Entity")]
    HierarchicalItems,
}

impl Related<super::contents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contents.def()
    }
}

impl Related<super::hierarchical_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HierarchicalItems.def()
    }
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
