//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod app_settings;
pub mod contents;
pub mod favorite_playlists;
pub mod folders;
pub mod hierarchical_items;
pub mod hierarchical_play_items;
pub mod items;
pub mod play_folders;
pub mod play_items;
pub mod playlists;
