//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "play_folders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub item_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hierarchical_play_items::Entity")]
    HierarchicalPlayItems,
    #[sea_orm(
        belongs_to = "super::play_items::Entity",
        from = "Column::ItemId",
        to = "super::play_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PlayItems,
}

impl Related<super::hierarchical_play_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HierarchicalPlayItems.def()
    }
}

impl Related<super::play_items::Entity> for Entity {
    fn to() -> RelationDef {
        super::hierarchical_play_items::Relation::PlayItems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::hierarchical_play_items::Relation::PlayFolders
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
