//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use improvie_domain::model::rules::RuleData;
use sea_orm::{FromJsonQueryResult, entity::prelude::*};
use serde::{Deserialize, Serialize};
use uid::Uid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "playlists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub item_id: Uid,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail_path: Option<String>,
    #[sea_orm(column_type = "custom(\"json\")")]
    pub rules: JsonRuleDataList,
}

#[derive(Clone, Debug, Serialize, Deserialize, FromJsonQueryResult, PartialEq, Eq)]
pub struct JsonRuleDataList(pub Vec<RuleData>);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::favorite_playlists::Entity")]
    FavoritePlaylists,
    #[sea_orm(
        belongs_to = "super::play_items::Entity",
        from = "Column::ItemId",
        to = "super::play_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PlayItems,
}

impl Related<super::favorite_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavoritePlaylists.def()
    }
}

impl Related<super::play_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
