//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "play_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "custom(\"tinyint unsigned\")")]
    pub kind: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hierarchical_play_items::Entity")]
    HierarchicalPlayItems,
    #[sea_orm(has_one = "super::play_folders::Entity")]
    PlayFolders,
    #[sea_orm(has_one = "super::playlists::Entity")]
    Playlists,
}

impl Related<super::hierarchical_play_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HierarchicalPlayItems.def()
    }
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Playlists.def()
    }
}

impl Related<super::play_folders::Entity> for Entity {
    fn to() -> RelationDef {
        super::hierarchical_play_items::Relation::PlayFolders.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::hierarchical_play_items::Relation::PlayItems
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
