// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentKind = "Video" | "Audio";

export type ItemKind = "Folder" | "Content";

export type PlayItemKind = "Folder" | "Playlist";
