// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileDialogKind = "Audio" | "Video" | "Image";

export type FileDialogResponse = { path: string, name: string, kind: FileDialogKind, };
