// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Uid } from "./uid";

export type ContentRule = { content_id: Uid, };

export type FolderRule = { target_folder_id: Uid, };

export type LoopRule = { rules: Array<RuleType>, times: number, };

export type RandomRule = { rules: Array<[RuleType, number]>, times: number, duplicate: boolean, };

export type RangeRule = { content_id: Uid, range_start: number | null, range_end: number | null, };

export type RuleFormat = { content_id: Uid, range_start: number | null, range_end: number | null, };

export type RuleType = { "type": "Content", "data": ContentRule } | { "type": "Range", "data": RangeRule } | { "type": "Loop", "data": LoopRule } | { "type": "Random", "data": RandomRule } | { "type": "Unknown" };
