// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RangeLimit = "None" | { "Min": number } | { "Max": number } | { "MinMax": [number, number] };
