// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YtVideoDownloadComplete = { video_path: string, thumbnail_path: string | null, };

export type YtVideoDownloading = { downloaded_mb: bigint, total_mb: bigint, percentage: number, };

export type YtVideoRequest = { process_id: string, file_name: string | null, video_url: string, audio_url: string, thumbnail_url: string | null, };

export type YtVideoState = { "type": "Idle", "data": { process_id: string, } } | { "type": "Downloading", "data": { process_id: string, state: YtVideoDownloading, } } | { "type": "Completed", "data": { process_id: string, state: YtVideoDownloadComplete, } };
