// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YtVideoDownloadComplete = { title: string, video_path: string, thumbnail_path: string | null, };

export type YtVideoDownloading = { downloaded_mb: bigint, total_mb: bigint, percentage: number, };

export type YtVideoRequest = { video_id: string, content_title: string, video_url: string, audio_url: string, thumbnail_url: string | null, };

export type YtVideoState = { "Idle": { video_id: string, } } | { "Downloading": { video_id: string, state: YtVideoDownloading, } } | { "Completed": { video_id: string, state: YtVideoDownloadComplete, } };
