// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YtPlaylistDownloadState = { index: number, state: YtVideoDownloadState, };

export type YtVideoDownloadState = { downloaded_mb: bigint, total_mb: bigint, percentage: number, };
