// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YtDownloadState = { downloaded_mb: bigint, total_mb: bigint, percentage: number, };
