name: 🐛 Bug Report
description: Please report any issues with the application.
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Please provide a description of the bug. (e.g. steps to reproduce, expected behavior, actual behavior)
