name: 🐛 Bug Report
description: Report an issue or unexpected behavior with the application.
title: "[BUG] "
labels: [bug]
assignees: moriyoshi-kasuga
body:
  - type: checkboxes
    id: duplicate
    attributes:
      label: Prior Issue Search
      description: Please confirm that you’ve checked for existing issues before reporting a new one.
      options:
        - label: I have searched for existing issues and couldn’t find a match.
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using? (e.g. Windows 11, macOS Ventura, Ubuntu 22.04)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Application Version
      description: Which version of the app are you using? (e.g. 1.0.0)
    validations:
      required: true

  - type: textarea
    id: issue-details
    attributes:
      label: Issue Details
      description: Please describe the issue, steps to reproduce it, and what you expected to happen.
      placeholder: |
        1. Describe the issue clearly and concisely.
        2. Provide detailed steps to reproduce the issue.
        3. Explain what you expected to happen instead.
    validations:
      required: true
