name: ✨ Feature Request
description: Suggest a new feature or improvement for the application.
title: "[FEATURE] "
labels: [enhancement]
assignees: moriyoshi-kasuga
body:
  - type: checkboxes
    id: duplicate
    attributes:
      label: Search for Existing Feature Requests
      description: Please confirm that you’ve checked for similar feature requests before creating a new one.
      options:
        - label: I have searched for similar requests and didn’t find any matches.
          required: true

  - type: textarea
    id: feature-details
    attributes:
      label: Feature Details
      description: Please describe the problem related to your feature request and the solution or improvement you propose.
      placeholder: |
        1. Describe the problem or inconvenience clearly.
        2. Suggest the feature or improvement you’d like to see.
    validations:
      required: true
