name: ❓ Question
description: Please fill in your questions regarding the project.
title: "[QUESTION] "
labels: [question]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provite context for your question.
