// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Uid } from "../uid";
import type { PlayFolder, PlayFolderNode, Playlist } from "./index";

export type CreateBasePlayItemDto = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreatePlayFolderDto = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreatePlayFolderResponse = { folder: PlayFolder, folder_node: PlayFolderNode, };

export type CreatePlaylistDto = { thumbnail_path: string | null, parent_folder_id: Uid, title: string, description: string | null, };

export type CreatePlaylistResponse = { playlist: Playlist, folder_node: PlayFolderNode, };
