// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Uid } from "../uid";

export type PlayFolder = { id: Uid, title: string, description: string | null, created_at: string, };

export type PlayFolderNode = { folder: Uid, children: Array<PlayItemNode>, };

export type PlayItem = { id: Uid, title: string, description: string | null, created_at: string, };

export type PlayItemNode = { "kind": "Folder", id: Uid, sort_order: number, } | { "kind": "Playlist", id: Uid, sort_order: number, };

export type Playlist = { thumbnail_path: string | null, id: Uid, title: string, description: string | null, created_at: string, };
