// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Uid } from "../uid";

export type CreateBasePlayItemRequest = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreatePlayFolderRequest = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreatePlaylistRequest = { thumbnail_path: string | null, parent_folder_id: Uid, title: string, description: string | null, };
