// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayFolder, PlayFolderNode, Playlist } from "./index";

export type CreatePlayFolderResponse = { folder: PlayFolder, folder_node: PlayFolderNode, };

export type CreatePlaylistResponse = { playlist: Playlist, folder_node: PlayFolderNode, };
