// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "../constants";
import type { Uid } from "../uid";
import type { Content, Folder, FolderNode } from "./index";

export type CreateBaseItemDto = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreateContentDto = { kind: ContentKind, content_path: string, thumbnail_path: string | null, seconds: number, parent_folder_id: Uid, title: string, description: string | null, };

export type CreateContentResponse = { content: Content, folder_node: FolderNode, };

export type CreateFolderDto = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreateFolderResponse = { folder: Folder, folder_node: FolderNode, };
