// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content } from "./index";
import type { ContentKind } from "../Constants";
import type { Folder } from "./index";
import type { FolderNode } from "./index";
import type { Uid } from "../Uid";

export type CreateBaseItemDto = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreateContentDto = { kind: ContentKind, content_path: string, thumbnail_path: string | null, parent_folder_id: Uid, title: string, description: string | null, };

export type CreateContentResponse = { content: Content, folder_node: FolderNode, };

export type CreateFolderDto = { parent_folder_id: Uid, title: string, description: string | null, };

export type CreateFolderResponse = { folder: Folder, folder_node: FolderNode, };
