// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "../constants";
import type { Uid } from "../uid";

export type Content = { kind: ContentKind, content_path: string, thumbnail_path: string | null, seconds: number, id: Uid, title: string, description: string | null, created_at: string, };

export type Folder = { id: Uid, title: string, description: string | null, created_at: string, };

export type FolderNode = { folder: Uid, items: Array<ItemNode>, };

export type Item = { id: Uid, title: string, description: string | null, created_at: string, };

export type ItemNode = { "kind": "Folder", id: Uid, sort_order: number, } | { "kind": "Content", id: Uid, sort_order: number, };
