// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "../constants";
import type { Uid } from "../uid";

export type CreateContentRequest = { kind: ContentKind, content_path: string, thumbnail_path: string | null, parent_folder_id: Uid, title: string, description: string | null, };
