// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content, Folder, FolderNode } from "./index";

export type CreateContentResponse = { content: Content, folder_node: FolderNode, };

export type CreateFolderResponse = { folder: Folder, folder_node: FolderNode, };
