name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y --no-install-recommends clang curl pkg-config ca-certificates

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target
          key: ci-rust-cache-${{ hashFiles('**/Cargo.lock') }}

      - name: Fmt
        run: |
          cd src-tauri
          cargo fmt --all -- --check

      - name: Clippy
        run: |
          cd src-tauri
          cargo clippy -- -D warnings

      - name: Run tests
        run: |
          cd src-tauri
          cargo ci

      - name: Check ts-binding diff
        run: |
          cd src
          git diff --exit-code -- bindings/

  frontned:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Bun modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-modules-${{ hashFiles('bun.lock') }}
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install frontend dependencies
        run: |
          bun install

      - name: Check frontend dependencies
        run: |
          bun run check

      - name: Test and Lint frontend
        run: |
          bun test
          bun run lint
