name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: tauri requirements # ref: https://tauri.app/start/prerequisites/#linux
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - name: Fmt
        run: |
          cd src-tauri
          cargo fmt --all -- --check

      - name: Clippy
        run: |
          cd src-tauri
          cargo clippy -- -D warnings

      - name: Run tests
        run: |
          cd src-tauri
          cargo ci

      - name: Check ts-binding diff
        run: |
          cd src
          git diff --exit-code -- bindings/

  frontned:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Bun modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-modules-${{ hashFiles('bun.lock') }}
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install frontend dependencies
        run: |
          bun install

      - name: Check frontend dependencies
        run: |
          bun run check

      - name: Test and Lint frontend
        run: |
          bun test
          bun run lint
