name: publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin

          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - platform: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Bun modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-modules-${{ hashFiles('bun.lock') }}
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install frontend dependencies
        run: |
          bun install

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target
          key: publish-rust-cache-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          # Install dependencies for tauri
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libwebkit2gtk-4.1-dev libasound2-dev libappindicator3-dev librsvg2-dev patchelf yasm
          # Install ffmpeg
          sudo apt-get install --no-install-recommends clang curl pkg-config xz-utils libxv-dev
          curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-lgpl-shared.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz
          echo "FFMPEG_DIR=$GITHUB_WORKSPACE/ffmpeg-master-latest-linux64-lgpl-shared" >> $GITHUB_ENV

      - name: install dependencies (mac only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install ffmpeg

      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
          Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
          Invoke-WebRequest "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z" -OutFile ffmpeg-release-full-shared.7z
          7z x ffmpeg-release-full-shared.7z
          mkdir ffmpeg
          mv ffmpeg-*/* ffmpeg/
          Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
          Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: App v__VERSION__
          releaseBody: See the assets to download this version and install.
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.target }} ${{ matrix.args }}
